name: Railway Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://html-e-java-simples-production.up.railway.app/

    steps:
      - name: Registrar deployment
        run: echo "Projeto publicado no Railway"
